[package]
name = "maplibre-build-tools"
version = "0.1.0"
description = "A library with build tools for maplibre-rs"
categories = []
edition = "2021"
authors = ["Maximilian Ammann <max@maxammann.org>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"

[features]
sqlite = ["rusqlite"]

[dependencies]
naga = { version = "0.8", features = ["wgsl-in"] }
walkdir = "2.3"
log = "0.4"
rusqlite = {version= "0.26", optional=true}
serde_json = "1.0"
flate2 = "1.0"
